site_name: PoShEvents
repo_url: https://github.com/thedavecarroll/PoShEvents
site_author: Dave Carroll
site_description:
google_analytics: ['UA-155184965-1', 'powershell.anovelidea.org']
edit_uri: edit/master/docs/
copyright: "PoShEvents is licensed under the <a href='https://github.com/thedavecarroll/PoShEvents/raw/master/LICENSE'>MIT license."
theme:
    name: material
nav:
- Home: README.md
- Change Log: ../CHANGELOG.md
- Functions:
    - Get-GPOProcessingEvent: Get-GPOProcessingEvent.md
    - ConvertFrom-EventLogRecord: ConvertFrom-EventLogRecord.md
